services:
  abinbev.employees.api:
    image: ${DOCKER_REGISTRY-}abinbevemployeesapi
    build:
      context: .
      dockerfile: ABInBev.Employees/Dockerfile
    networks:
      - app-network
  abinbev.employees.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ABInBev.Employees.DB
    environment:
      - SA_PASSWORD=Pass@word1
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge